# -*- coding: utf-8 -*-
"""ML lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ranN51y9RAoREroacCVTohjoiTkG6uYp
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.linspace(-10,10,1000)
w=np.linspace(-10,10,1000)



def function(x,w):

  for i in range(10):
    y_pred=x*w[i]
    
  return y_pred

y_pred=function(x,w)



plt.plot(y_pred)

y=np.linspace(-10,10,1000)

print(y)



def loss_fn(x,y,w):
  loss=(y_pred-y)**2

 
  return loss

s=loss_fn(y_pred,y,w)


plt.plot(w,s)











